- CHANGES.txt
- src/plone/app/robotframework/users.py
Read security settings from the registry instead of portal properties. This is part of work on the security control panel migration: https://github.com/plone/Products.CMFPlone/issues/216
This should be merged along with https://github.com/plone/Products.CMFPlone/pull/362
> Plip 10359 - Security Control Panel migration

- CHANGES.txt
- setup.py
- src/plone/app/robotframework/server.py
Replace import of zope.testing.testrunner with zope.testrunner.
Newer zope.testing.testrunner is deprecated.
This one is for Zope 4 compatibility.
> Zope 4 compatibility

- CHANGES.txt
- setup.py
> Do not require argparse, decorator, and simplejson in Python 2.7.

- CHANGES.rst
- src/plone/app/robotframework/content.py
The format of the second parameter on ObjectModifiedEvent can't be a dict. It must be an Attributes instance: ObjectModifiedEvent(obj, Attributes(ISample, "field")) (zope.lifecycleevent.__init__.py).
As we can't have the field interface or the full fieldname, we can't add an Attributes instance. 
I have removed the parameter...
> Removed bad format parameter on ObjectModifiedEvent

- CHANGES.rst
- src/plone/app/robotframework/selenium.robot
This interferes with Wait until keyword succeeds: an initial failure
is seen as total failure instead of checking the retries of this
keyword.
Added `Plone Test Setup` and `Plone Test Teardown` keywords.  In that
last one, in case of a failure do what used to be done by
run_on_failure.  This means a screen shot by default, but you can
override this on the command line with for example
ROBOT_SELENIUM_RUN_ON_FAILURE=Debug, or Nothing to ignore it.
See https://github.com/plone/Products.CMFPlone/pull/1652
> Do not use run_on_failure from Selenium2Library.

- CHANGES.rst
- src/plone/app/robotframework/tests/test_content_library.robot
This fixes a warning in Travis (or locally): `[ WARN ] Keyword 'DeprecatedBuiltIn.Fail Unless Equal' is deprecated. Use 'BuiltIn.Should Be Equal' instead.`
See https://travis-ci.org/plone/plone.app.robotframework/jobs/142141481
> Replaced deprecated `Fail Unless Equal` with `Should Be Equal` in test.

- CHANGES.rst
- src/plone/app/robotframework/quickinstaller.py
That will work on Plone 5.1+.
Fall back to getting the `portal_quickinstaller` tool on earlier Plones.
> Use `get_installer` for checking if a product is installed.

- CHANGES.rst
- setup.py
- src/plone/app/robotframework/autologin.py
Requires PlonePAS 5.0.1 (by default included since Plone 5.3.8).
> Import activatePluginInterfaces from Products.PlonePAS.setuphandlers.

- CHANGES.rst
- src/plone/app/robotframework/tests/test_users_library.robot
- src/plone/app/robotframework/users.py
Issue https://github.com/plone/plone.app.robotframework/issues/77
1. `Create user  siteadmin  Contributor  Reviewer  Site Administrator`
2. `Create user  siteadmin2  roles=('Contributor','Reviewer','Site Administrator')`
None of the two creates a user as expected.
1. creates a user with roles ('Member',)
2. creates a user with roles ('Contributor','Reviewer','Site Administrator'), missing role 'Member'
> Create user with roles

- CHANGES.rst
- src/plone/app/robotframework/variables.py
A simple backport of the change from 1.3.x.
> Default to picking a free port - backport to 1.2.x

- CHANGES.rst
- src/plone/app/robotframework/variables.py
@Rotonen this is missing so that 5.0 jobs do work as well. sorry the previous one was wrong.
> Default to picking a free port.

- CHANGES.rst
- src/plone/app/robotframework/server.py
When starting the robot server, the ports for the ZServer and for the XMLRPC-server can be configured to 0 in order to let the operating system choose a random open port.
When the ports are randomly chosen, it is helpful that the server prints out the chosen ports in form of URLs, so that a caller may read the URLs in order to connect to the servers.
This is a back port for Plone 4; Plone 5 version: #106
> Print ZServer and XMRPC URLs on server startup (Plone 4).

- CHANGES.rst
- src/plone/app/robotframework/server.py
When starting the robot server, the ports for the ZServer and for the XMLRPC-server can be configured to 0 in order to let the operating system choose a random open port.
When the ports are randomly chosen, it is helpful that the server prints out the chosen ports in form of URLs, so that a caller may read the URLs in order to connect to the servers.
Back ported to Plone 4: #105
> Print ZServer and XMRPC URLs on server startup (Plone 5).

- news/2786.bugfix
- src/plone/app/robotframework/__init__.py
- src/plone/app/robotframework/patches.py
This retries once when we get a ConnectionResetError (which is a `builtin` in Python 3 and does not exist yet on Python 2).
Fixes https://github.com/plone/Products.CMFPlone/issues/2786.
> Patch selenium.is_connectable for Python 3 for ConnectionResetError

- docs/source/happy.rst
- news/110.bugfix
- src/plone/app/robotframework/selenium.robot
- src/plone/app/robotframework/tests/docs/test_hello.robot
- src/plone/app/robotframework/tests/docs/test_keywords.robot
- src/plone/app/robotframework/tests/test_autologin_library.robot
- src/plone/app/robotframework/tests/test_content_library.robot
- src/plone/app/robotframework/tests/test_i18n_library.robot
- src/plone/app/robotframework/tests/test_robotfixture.robot
- src/plone/app/robotframework/tests/test_speakjs_library.robot
- src/plone/app/robotframework/tests/test_users_library.robot
The largest categories of Robot test flakiness we have are:
1) Things being unclickable by being outside the browser viewport
2) Interactive elements, like form buttons, collapsing into themselves in a way where they overlap in a mobile view
Both are caused by the default window size being a rather arcane 800 x 600. (Or in the case of Xvfb, also limited by the default desktop size and color depth of 640x480x8). In some cases, with Xvfb, the browser defaults, for unknown reasons, to a window size of 1024x768. None of these represent contemporary actual use very well.
The usability issues, especially the mobile ones, can be real usability issues and should thus be eventually tackled. I deem stable tests more valuable *at this point in time*. Currently these issues manifest mostly for people …
> Default to a 4K x 4K browser window

- CHANGES.rst
- src/plone/app/robotframework/keywords.robot
Revert "Selector of login form matches text"
This reverts commit 9f80a05edceb71ae91e6da4dc69d353f4763863c.
Fixes https://github.com/plone/plone.app.robotframework/issues/107
> Reverted change in 1.2.1 for 'Log in' keyword which failed in Plone 4.3.

- news/114.fixed
- src/plone/app/robotframework/keywords.robot
> Fix the Debug keyword

- news/680.bugfix
- src/plone/app/robotframework/variables.py
This is some example selector.
On Plone 6 the variable was not defined.
It makes all robot tests on Plone 6 broken, see https://github.com/plone/buildout.coredev/pull/680
```
[ ERROR ] Error in file
'/Users/maurits/community/plone-coredev/6.0/src/plone.app.robotframework/src/plone/app/robotframework/selenium.robot':
Replacing variables from setting 'Resource' failed: Variable '${CMFPLONE_SELECTORS}' not found.
```
> Fixed error "Variable '${CMFPLONE_SELECTORS}' not found" on Plone 6.

- news/1775.feature
- src/plone/app/robotframework/quickinstaller.py
Current plone.app.robotframework is only for Plone 5.2+, so this code was no longer used.
See also PLIP 1775: https://github.com/plone/Products.CMFPlone/issues/1775.
Can be tested and merged on its own.
> Removed backwards compatibility code for old quickinstaller.

- news/3813.feature
- setup.py
- src/plone/app/robotframework/browser.robot
- src/plone/app/robotframework/tests/test_browser_library.robot
- src/plone/app/robotframework/tests/test_robot.py
__Big disclaimer:__ I'm (@gforcada) merely the one that created the PR, the code and credits for this feature, as commits show, goes to @datakurre ✨ 💯 
⚠️ It needs the version pins defined on [this buildout.coredev branch](https://github.com/plone/buildout.coredev/tree/datakurre-rfbrowser).
Part of https://github.com/plone/Products.CMFPlone/issues/3813
> Support playwright based robot tests via robotframework-browser extension

- news/154.bugfix
- src/plone/app/robotframework/testing.py
In Plone 6, the plone.app.contenttypes profile is already installed by the PLONE_FIXTURE. So it's not necessary for SimplePublicationLayer to install it again.
This avoids printing a warning that plone.app.event is already installed, and avoids some unnecessary work.
> Avoid duplicate installation of plone.app.contenttypes profile

- news/155.bugfix
- src/plone/app/robotframework/server.py
When robot-server starts without reloading enabled (including when it runs in the plone/server-acceptance container), it tries to print the URL where the server is accepting HTTP requests. But, this only worked for ZServer-based layers and not WSGI server-based layers.
> Fix printing the server URL in non-reload mode
